networks:
  template-network:
    name: simplenet
    external: true

services:

  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./:/opt/app"
      - "./rootfs/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE
    networks:
      template-network:

  nginx:
    image: nginx:alpine
    ports:
      - "9001:9001"
    volumes:
      - "./:/opt/app"
      - "./rootfs/etc/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      - PORT=9001
      - HOST=api.url
    networks:
      template-network:
        aliases:
          - api.url
