networks:
  template-network:
    name: simplenet
    external: true

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/opt/app'
    ports:
      - '9002:9002'
    command: /bin/bash -c "npm i && npm run dev -- --host 0.0.0.0 --port 9002"
    networks:
      template-network:
        aliases:
          - 'app.url'